language: node_js
node_js: 
- 8.9.4

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g mocha 
  - npm install

   
script:
  - npm test

after_success:
  - npm run coveralls
  
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

