language: node_js
node_js: 
- 8.11.1

cache:
  directories:
    - "node_modules"


before_install:
  - npm install -g mocha 
  - npm install

before_script:
    
script:
  - npm run test

after_success:
  - npm run coveralls
  
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

